# Generated by Django 5.0.2 on 2024-02-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wps_app', '0002_actor_alter_match_goals1_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='caps',
            field=models.ManyToManyField(blank=True, null=True, related_name='matches', to='wps_app.person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='wps_app.actor'),
        ),
    ]
